### ISSUE TITLE
关于硬件

### ISSUE THREAD

**Issue by Abraham423** [peng-zhihui/XUAN-Bike#3]

**Comment by Abraham423** [comment]
请问硬件是怎么获取的呢，通过cad画出图纸，然后请工厂代工的吗？

**Comment by SummerFalls** [comment]
> 请问硬件是怎么获取的呢，通过cad画出图纸，然后请工厂代工的吗？

以 `Altium Designer 21` 版本举例，通过它画好 PCB 之后，导出设计文件（Gerber、钻孔文件、IPC网表），如果你要贴片则还需要额外导出坐标文件、BOM表；以上步骤做完之后可以到打板厂下单，比如：嘉立创、捷多邦…，先将你的设计文件打包压缩成zip，之后上传到相应打板厂的网站下单，选定相关工艺参数之后，填收货地址然后付钱就可以了

**Comment by kaixin8850** [comment]
为啥下载不了那
