### ISSUE TITLE
关于AI芯片

### ISSUE THREAD

**Issue by wujialiang** [peng-zhihui/XUAN-Bike#7]
请问稚晖君大佬，项目中用的昇腾310核心板预计可以做多少的成本呢？我也想搞一块玩一下 ^_^

**Comment by wujialiang** [comment]
我这边听别人说整套做下来成本是1-3w左右？我这边有个脑洞想法，稚晖君能否搞个五菱宏光miniEV上做这种改造呢？*_*

**Comment by stonexing** [comment]
树莓派可以代替这款芯片吗？

**Comment by APX103** [comment]
> 请问稚晖君大佬，项目中用的昇腾310核心板预计可以做多少的成本呢？我也想搞一块玩一下 ^_^

这玩意有卖，可以买atlas200dk，拆出来就是了~

**Comment by peng-zhihui** [comment]
昇腾310的模组A200目前比较难买。实际上我在公司有负责一个新的边缘板卡项目（对标Nvidia Jetson的），性价比会高很多，但是由于芯片方面众所周知的原因，这个产品可能还需要一阵子才能面市，所以大家感兴趣的话可以保持关注。
